AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CY Lambda's

Resources:

  # IAM role

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "LambdaRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - Sub "arn:aws:logs:${AWS::Region}:*:*"
              -
                Effect: "Allow"
                Action:
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeTags"
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DeleteNetworkInterface"
                Resource:
                  - "*"

  # Lambda

  DummyLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaRole
    Properties:
      LogGroupName: dummy
      RetentionInDays: 1

  CYDemoLambda:
    Type: 'AWS::Serverless::Function'
    DependsOn: LambdaRole
    Properties:
      FunctionName: "CYDemoLambda"
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role:
        Fn::GetAtt:
          - "LambdaRole"
          - "Arn"
      VpcConfig:
        SubnetIds:
          - subnet-7421e91f
          - subnet-e3131a99
        SecurityGroupIds:
          - sg-0a9aeeb3e7d9825de
      Events:
        GetByPathApi:
          Type: Api
          Properties:
            Path: /persons/{id}
            Method: GET
            RestApiId: !Ref MyApi
        GetByQueryApi:
          Type: Api
          Properties:
            Path: /persons
            Method: GET
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: eu-central-1


  # Api

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "TestAPI"
        paths:
          /persons:
            get:
              parameters:
              - name: "id"
                in: "query"
                required: true
                type: "string"
              x-amazon-apigateway-request-validator: "Validate query string parameters and headers"
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CYDemoLambda.Arn}/invocations
                responses: {}
                httpMethod: "POST"
                type: "aws_proxy"
          /persons/{id}:
            get:
              parameters:
              - name: "id"
                in: "path"
                required: true
                type: "string"
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CYDemoLambda.Arn}/invocations
                responses: {}
                httpMethod: "POST"
                type: "aws_proxy"
        x-amazon-apigateway-request-validators:
          Validate query string parameters and headers:
            validateRequestParameters: true
            validateRequestBody: false
